### ISSUE TITLE
Fix nodes being down alerts spam

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/infra#95]
The nodes are being restarted automatically, so down times are a norm. We need to switch alerting from based on Prometheus' `up` metric to one of Stackdriver's, which can tell crash from restart.

Notes from @geigerzaehler:

> One issue we have with the current setup is that we get false alerts for nodes being down when miners are pre-empted. To check miner availability we need to distinguish between nodes being down because its pod is rescheduled due to a VM being pre-empted and a node being down because it has crashed.
>
> I found that kube-state-metrics [exposes](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) a metric for a the [pod phase](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase). We could use the “Failed” status of that metrics to determine whether a node crashed.

**Comment by geigerzaehler** [comment]
> We need to switch alerting from based on Prometheus' `up` metric to one of Stackdriver's, which can tell crash from restart.

Unfortunately StackDriver cannot discriminate between crashes and other restarts either. Only `kube-state-metrics` can do this and this service is not running on our cluster. I’d suggest we add it to the cluster and scrape it with prometheus so that we can create grafana dashboards. Until this is done we should probably just be more lenient with the `up` metrics and only alert when a node is down for more than 4 minutes. This value is just on the edge of the time kubernetes takes to reschedule a pod.

**Comment by CodeSandwich** [comment]
We have this mitigated by monitoring for downtimes longer than 4 minutes. Do we need a better fix, os is it good enough and we consider this issue closed?

**Comment by geigerzaehler** [comment]
I’m ok with closing this.
